# Generated by Django 5.1.1 on 2024-09-09 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_developer_alter_game_options_alter_game_developer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='developer',
            options={'verbose_name': 'Разработчик', 'verbose_name_plural': 'Разработчики'},
        ),
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
    ]
