# Generated by Django 5.1.1 on 2024-09-10 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_developer_options_remove_game_developer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.AddField(
            model_name='game',
            name='genre_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.genre'),
        ),
    ]
