# Generated by Django 5.1.1 on 2024-09-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_genre_game_genre_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Платформа')),
            ],
            options={
                'verbose_name': 'Платформа',
                'verbose_name_plural': 'Платформы',
            },
        ),
    ]
