# Generated by Django 5.1.1 on 2024-09-10 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_platform_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryDevelop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Страна разработки')),
            ],
            options={
                'verbose_name': 'Страна разработки',
                'verbose_name_plural': 'Страны разработки',
            },
        ),
        migrations.AddField(
            model_name='developer',
            name='country_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='games.countrydevelop'),
        ),
    ]
