# Generated by Django 5.1.1 on 2024-10-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_countrydevelop_developer_country_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='picture',
            field=models.ImageField(null=True, upload_to='games', verbose_name='Изображение'),
        ),
    ]
