# Generated by Django 5.1.1 on 2024-10-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_game_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrydevelop',
            name='picture',
            field=models.ImageField(null=True, upload_to='country_developer', verbose_name='Изображение'),
        ),
    ]
